beto-rodriguez/LiveCharts2

src/skiasharp/LiveChartsCore.SkiaSharp/Painting/GradientPaintTask.cs
Closes #14. Added a gradient paint task.
Any ideas for how abstract the paint task should be? I.e. if it is created from a `GradientDirection` enum, radians/degrees, vector?
=> Add gradient paint task

samples/BlazorSample/wwwroot/css/app.css
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/beto-rodriguez/livecharts2/issues/master).
=> Apply fixes from CodeFactor

samples/XamarinSample/XamarinSample/XamarinSample.Android/Resources/Resource.designer.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.Blazor/LiveChartsCore.SkiaSharpView.Blazor.csproj, src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/DefaultTooltip.xaml.cs
Rectangle has been changed to Rect in Maui
=> Fix Build issue with Maui

src/LiveChartsCore/Kernel/Sketches/IPieChartView.cs, src/LiveChartsCore/PieSeries.cs, src/skiasharp/LiveChartsCore.SkiaSharp.Avalonia/PieChart.axaml.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WPF/PieChart.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WinForms/PieChart.cs, src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/PieChart.xaml.cs, src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKPieChart.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.Blazor/PieChart.razor.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.Eto/PieChart.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/PieChart.xaml.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.Uno.WinUI/PieChart.xaml.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.Uno/PieChart.xaml.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/PieChart.xaml.cs
=> Anticlockwise pie

.github/workflows/run-unit-tests.yml, src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs, src/LiveChartsCore/Series.cs, src/skiasharp/LiveChartsCore.SkiaSharp/HeatSeries.cs, src/skiasharp/LiveChartsCore.SkiaSharp/LiveChartsSkiaSharp.cs, tests/LiveChartsCore.UnitTesting/ColumnSeriesTest.cs, tests/LiveChartsCore.UnitTesting/FinancialSeriesTest.cs, tests/LiveChartsCore.UnitTesting/HeatSeriesTest.cs, tests/LiveChartsCore.UnitTesting/LineSeriesTest.cs, tests/LiveChartsCore.UnitTesting/LiveChartsCore.UnitTesting.csproj, tests/LiveChartsCore.UnitTesting/MockedObjects/TestCartesianChartView.cs, tests/LiveChartsCore.UnitTesting/PieSeriesTest.cs, tests/LiveChartsCore.UnitTesting/PolarLineSeriesTest.cs, tests/LiveChartsCore.UnitTesting/RowSeriesTest.cs, tests/LiveChartsCore.UnitTesting/ScatterSeriesTest.cs, tests/LiveChartsCore.UnitTesting/StackedAreaSeriesTest.cs, tests/LiveChartsCore.UnitTesting/StackedColumnSeriesTest.cs, tests/LiveChartsCore.UnitTesting/StackedRowSeriesTest.cs, tests/LiveChartsCore.UnitTesting/StackedStepAreaSeriesTest.cs, tests/LiveChartsCore.UnitTesting/StepLineSeriesTest.cs
It is now easier to unit test the series in the UI; this PR adds multiple useful missing tests.
=> Better unit tests

samples/ViewModelsSamples/Axes/LabelsRotation/ViewModel.cs, src/LiveChartsCore/Drawing/ILabelGeometry.cs, src/skiasharp/LiveChartsCore.SkiaSharp/Drawing/Geometries/LabelGeometry.cs, src/skiasharp/LiveChartsCore.SkiaSharp/VisualElements/LabelVisual.cs, tests/LiveChartsCore.UnitTesting/LabelsMeasureTest.cs
=> Improves multiline labels measure

samples/MauiSample/Events/AddPointOnClick/View.xaml, samples/MauiSample/Events/AddPointOnClick/View.xaml.cs, samples/MauiSample/General/Scrollable/View.xaml, src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/CartesianChart.xaml.cs
=> Improve events and commands

samples/MauiSample/Axes/CustomSeparatorsInterval/View.xaml, samples/MauiSample/Axes/CustomSeparatorsInterval/View.xaml.cs, samples/MauiSample/Axes/Multiple/View.xaml, samples/MauiSample/Axes/Multiple/View.xaml.cs, src/LiveChartsCore/Axis.cs, src/LiveChartsCore/Drawing/Padding.cs, src/skiasharp/LiveChartsCore.SkiaSharp/Drawing/Geometries/CandlestickGeometry.cs, src/skiasharp/LiveChartsCore.SkiaSharp/Drawing/Geometries/DoughnutGeometry.cs, src/skiasharp/LiveChartsCore.SkiaSharp/Drawing/Geometries/Geometry.cs, src/skiasharp/LiveChartsCore.SkiaSharp/Drawing/Geometries/LabelGeometry.cs, src/skiasharp/LiveChartsCore.SkiaSharp/Drawing/Geometries/LineGeometry.cs, src/skiasharp/LiveChartsCore.SkiaSharp/Drawing/Geometries/SizedGeometry.cs, src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKDefaultLegend.cs, src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKDefaultTooltip.cs, tests/LiveChartsCore.UnitTesting/SeriesTests/ScatterSeriesTest.cs
Improves labels measure/positioning, this  improvement is noticeable on Mac.
=> Fix labels

src/LiveChartsCore/Kernel/LiveChartsSettings.cs, src/skiasharp/LiveChartsCore.SkiaSharp/Drawing/Geometries/LabelGeometry.cs, src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKDefaultTooltip.cs
=> Improves rtl rendering

src/LiveChartsCore/PieSeries.cs, tests/LiveChartsCore.UnitTesting/SeriesTests/PieSeriesTest.cs
fixes #1139
fixes #1135
fixes #1096
=> Adds more tests to pie labels

samples/AvaloniaSample/Bars/Race/View.axaml.cs, samples/BlazorSample/Pages/Bars/Race.razor, samples/EtoFormsSample/Bars/Race/View.cs, samples/MauiSample/Bars/Race/View.xaml.cs, samples/UnoPlatformSample/UnoPlatformSample/LiveChartsSamples/Bars/Race/View.xaml.cs, samples/ViewModelsSamples/Bars/Race/ViewModel.cs, samples/ViewModelsSamples/General/MultiThreading/ViewModel.cs, samples/ViewModelsSamples/General/MultiThreading2/ViewModel.cs, samples/WPFSample/Bars/Race/View.xaml.cs, samples/WinFormsSample/Bars/Race/View.cs, samples/WinUISample/WinUISample/Bars/Race/View.xaml.cs, samples/XamarinSample/XamarinSample/XamarinSample/Bars/Race/View.xaml.cs, src/LiveChartsCore/Chart.cs, src/LiveChartsCore/VisualElements/RelativePanel.cs
Fixes memory leaks.
- fixes #1080 
- fixes #1147
=> Memory review

docs/samples/lines/zoom/template.md, samples/AvaloniaSample/Lines/Zoom/View.axaml, samples/MauiSample/AppShell.xaml.cs, samples/MauiSample/Lines/Zoom/View.xaml, samples/UWPSample/Lines/Zoom/View.xaml, samples/UnoPlatformSample/UnoPlatformSample/LiveChartsSamples/Lines/Zoom/View.xaml, samples/WPFSample/Lines/Zoom/View.xaml, samples/WinUISample/WinUISample/Lines/Zoom/View.xaml, samples/XamarinSample/XamarinSample/XamarinSample/Lines/Zoom/View.xaml, src/skiasharp/LiveChartsCore.SkiaSharp.WPF/CartesianChart.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/CartesianChart.xaml, src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/CartesianChart.xaml.cs
Implements zooming on MAUI desktop devices.
-fixes #635
=> Maui events

samples/ViewModelsSamples/Pies/AngularGauge/ViewModel.cs, src/LiveChartsCore/Kernel/Sketches/IPieSeries.cs, src/LiveChartsCore/PieChart.cs, src/LiveChartsCore/PieSeries.cs, src/LiveChartsCore/VisualElements/AngularTicksVisual.cs, src/skiasharp/LiveChartsCore.SkiaSharp/Extensions/GaugeGenerator.cs, src/skiasharp/LiveChartsCore.SkiaSharp/Extensions/PieChartExtensions.cs
=> Fixes to angula gauges

src/LiveChartsCore.Behaviours/ChartBehaviour.Android.cs, src/LiveChartsCore.Behaviours/ChartBehaviour.MacCatalyst.cs
=> Improves user interaction with the charts

src/LiveChartsCore/BarSeries.cs, src/LiveChartsCore/CoreAxis.cs, src/LiveChartsCore/CoreFinancialSeries.cs, src/LiveChartsCore/CoreHeatSeries.cs, src/LiveChartsCore/CoreLineSeries.cs, src/LiveChartsCore/CorePieSeries.cs, src/LiveChartsCore/CorePolarAxis.cs, src/LiveChartsCore/CorePolarLineSeries.cs, src/LiveChartsCore/CoreStepLineSeries.cs, src/LiveChartsCore/DrawMarginFrame.cs, src/LiveChartsCore/Kernel/ChartElement.cs, src/LiveChartsCore/Section.cs, src/LiveChartsCore/StrokeAndFillCartesianSeries.cs, src/LiveChartsCore/VisualElements/AngularTicksVisual.cs, src/LiveChartsCore/VisualElements/BaseGeometryVisual.cs, src/LiveChartsCore/VisualElements/GeometryVisual.cs, src/LiveChartsCore/VisualElements/LabelVisual.cs, src/LiveChartsCore/VisualElements/NeedleVisual.cs, src/LiveChartsCore/VisualElements/RelativePanel.cs, src/LiveChartsCore/VisualElements/StackPanel.cs, src/LiveChartsCore/VisualElements/TableLayout.cs, src/LiveChartsCore/VisualElements/VariableGeometryVisual.cs, src/LiveChartsCore/VisualElements/VisualElement.cs
=> refactor accesibility

samples/ViewModelsSamples/Axes/Crosshairs/ViewModel.cs, samples/ViewModelsSamples/Axes/Shared/ViewModel.cs, src/LiveChartsCore/CartesianChart.cs, src/LiveChartsCore/Chart.cs, src/LiveChartsCore/CoreAxis.cs, src/LiveChartsCore/Kernel/Providers/ChartEngine.cs, src/LiveChartsCore/Kernel/Sketches/ICartesianAxis.cs, src/LiveChartsCore/SharedAxes.cs, src/skiasharp/LiveChartsCore.SkiaSharp.Avalonia/CartesianChart.axaml.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WPF/CartesianChart.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WinForms/CartesianChart.cs, src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/CartesianChart.xaml.cs, src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKCartesianChart.cs, src/skiasharp/LiveChartsCore.SkiaSharp/SkiaSharpProvider.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.Blazor/CartesianChart.razor.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.Eto/CartesianChart.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/CartesianChart.xaml.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.Uno.WinUI/CartesianChart.xaml.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/CartesianChart.xaml.cs
Fixes axes related issues:
- #1644 
- #876
- #1438
=> Axes fixes

samples/AvaloniaSample/Pies/Icons/View.axaml, samples/AvaloniaSample/Pies/Icons/View.axaml.cs, samples/BlazorSample/Pages/Pies/Icons.razor, samples/EtoFormsSample/Pies/Icons/View.cs, samples/MauiSample/Pies/Icons/View.xaml, samples/MauiSample/Pies/Icons/View.xaml.cs, samples/UnoPlatform_v5/UnoPlatform_v5/LiveChartsSamples/Pies/Icons/View.xaml, samples/UnoPlatform_v5/UnoPlatform_v5/LiveChartsSamples/Pies/Icons/View.xaml.cs, samples/ViewModelsSamples/Index.cs, samples/ViewModelsSamples/Pies/Icons/ViewModel.cs, samples/WPFSample/Pies/Icons/View.xaml, samples/WPFSample/Pies/Icons/View.xaml.cs, samples/WinFormsSample/Pies/Icons/View.Designer.cs, samples/WinFormsSample/Pies/Icons/View.cs, samples/WinFormsSample/Pies/Icons/View.resx, samples/WinUISample/WinUISample/Pies/Icons/View.xaml, samples/WinUISample/WinUISample/Pies/Icons/View.xaml.cs, samples/XamarinSample/XamarinSample/XamarinSample/Pies/Icons/View.xaml, samples/XamarinSample/XamarinSample/XamarinSample/Pies/Icons/View.xaml.cs
Now with a more stable api, an example for #995
=> Add example to build #995

tests/LiveChartsCore.UnitTesting/SeriesTests/_MemoryTests.cs
New tests to prevent the new changes introduce new memory leaks.
=> Memory tests

samples/WinUISample/WinUISample/WinUISample.csproj, src/LiveChartsCore.Behaviours/LiveChartsCore.Behaviours.csproj, src/LiveChartsCore/LiveChartsCore.csproj, src/skiasharp/LiveChartsCore.SkiaSharp.WPF/LiveChartsCore.SkiaSharpView.WPF.csproj, src/skiasharp/LiveChartsCore.SkiaSharp.WinForms/LiveChartsCore.SkiaSharpView.WinForms.csproj, src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/LiveChartsCore.SkiaSharpView.Xamarin.Forms.csproj, src/skiasharp/LiveChartsCore.SkiaSharp/LiveChartsCore.SkiaSharpView.csproj, src/skiasharp/LiveChartsCore.SkiaSharp/Painting/ImageFilters/Blur.cs, src/skiasharp/LiveChartsCore.SkiaSharp/Painting/ImageFilters/DropShadow.cs, src/skiasharp/LiveChartsCore.SkiaSharp/Painting/ImageFilters/ImageFiltersMergeOperation.cs, src/skiasharp/LiveChartsCore.SkiaSharpView.Blazor/LiveChartsCore.SkiaSharpView.Blazor.csproj, src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/LiveChartsCore.SkiaSharpView.Maui.csproj, src/skiasharp/LiveChartsCore.SkiaSharpView.Uno.WinUI/LiveChartsCore.SkiaSharpView.Uno.WinUI.csproj, src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/LiveChartsCore.SkiaSharpView.WinUI.csproj
Updates the library to SkiaSharp 3
- fixes #1580
Requires package source; `https://aka.ms/skiasharp-eap/index.json`
=> SkiaSharp 3

src/skiasharp/LiveChartsCore.SkiaSharp.WPF/CartesianChart.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WPF/Chart.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WPF/GeoMap.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WPF/MotionCanvas.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WPF/PieChart.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WPF/PolarChart.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WPF/Themes/Generic.xaml, src/skiasharp/LiveChartsCore.SkiaSharp.WinForms/Chart.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WinForms/GeoMap.Designer.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WinForms/MotionCanvas.Designer.cs, src/skiasharp/LiveChartsCore.SkiaSharp.WinForms/MotionCanvas.cs
This PR continues https://github.com/beto-rodriguez/LiveCharts2/pull/1685
=> Continue #1685

src/LiveChartsCore/CartesianSeries.cs, src/LiveChartsCore/CoreBoxSeries.cs, src/LiveChartsCore/CoreFinancialSeries.cs, src/LiveChartsCore/CoreRowSeries.cs, src/LiveChartsCore/Defaults/FinancialPoint.cs, src/LiveChartsCore/Defaults/FinancialPointI.cs, src/LiveChartsCore/Kernel/Extensions.cs
Improves series/axes range when only one point is visible
fixes #1677
=> Axis range

src/LiveChartsCore/VisualElements/BaseAngularTicksVisual.cs, src/LiveChartsCore/VisualElements/BaseLabelVisual.cs, src/LiveChartsCore/VisualElements/BaseNeedleVisual.cs, src/LiveChartsCore/VisualElements/VisualElement.cs, src/skiasharp/LiveChartsCore.SkiaSharp/ThemesExtensions.cs, src/skiasharp/LiveChartsCore.SkiaSharp/VisualElements/AngularTicksVisual.cs, src/skiasharp/LiveChartsCore.SkiaSharp/VisualElements/LabelVisual.cs, src/skiasharp/LiveChartsCore.SkiaSharp/VisualElements/NeedleVisual.cs
This allows to apply themes to derived VisualElements.
=> Refactor visual classes to use new abstract base classes
