beto-rodriguez/LiveCharts2

- src/LiveChartsCore/LineSeries.cs
- src/LiveChartsCore/Measure/Scaler.cs
- src/LiveChartsCore/RowSeries.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.WPF/CartesianChart.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.WPF/Chart.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.WPF/DefaultTooltip.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.WPF/PieChart.cs
Use of SetValue during initialization prevented templates from setting their own values on those properties.
Replaced property assignments with calls to SetCurrentValue, and added explicit interface implementations that use SetCurrentValue during initialization.
Added CoerceValueCallback to the Series and Axes properties to ensure they are not set to null.
> (WPF) Fixes for use in templates

- docs/LiveChartsCore.SkiaSharpView.xml
- docs/LiveChartsCore.xml
- src/LiveChartsCore/Axis.cs
- src/LiveChartsCore/Drawing/IDrawableTask.cs
- src/LiveChartsCore/Kernel/DefaultPaintTask.cs
- src/LiveChartsCore/PieSeries.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.WPF/MotionCanvas.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.WPF/Themes/Generic.xaml
- src/skiasharp/LiveChartsCore.SkiaSharp/Painting/PaintTask.cs
- Fixed pie charts breaking if their total is 0 at any point.
- Fixed axes retaining their previous separator visuals when removed and re-added to a chart.
- Fixed display scaling not being applied in WPF (already works for the other frameworks.)
> Couple of small fixes

- src/skiasharp/LiveChartsCore.SkiaSharp.WPF/MotionCanvas.cs
Make sure `MotionCanvas` is correctly re-initialized after being unloaded then re-loaded.
Fixes #108
> Fix MotionCanvas to support dynamic loading/unloading

- src/skiasharp/LiveChartsCore.SkiaSharpVew.WinUI/MotionCanvas.xaml.cs
@beto-rodriguez I don't have my machine set up for WinUI testing, so **I haven't done any testing on this**, but it looks like the same issue with loading/unloading the `MotionCanvas` might also exist for that platform.
Feel free to mark this PR as ready/merge it if it looks good.
> Allow WinUI MotionCanvas to be unloaded/re-loaded correctly

- src/LiveChartsCore/Defaults/DateTimePoint.cs
The `Value` property in `DateTimePoint` is already nullable, this PR just changes the associated constructor parameter to match
> Support null values in DateTimePoint constructor

- src/LiveChartsCore/CartesianChart.cs
- src/LiveChartsCore/Kernel/Extensions.cs
- src/LiveChartsCore/Kernel/TooltipPoint.cs
- src/LiveChartsCore/Series.cs
Solving issue https://github.com/beto-rodriguez/LiveCharts2/issues/100
> Bugfix 100

- src/LiveChartsCore/Section.cs
The existing cast to float was unnecessary since the `ToPixels()` method accepts a `double` value. The loss of precision from this unnecessary cast was causing incorrect scaling for some values
> Scale `Section` coordinates correctly

- src/LiveChartsCore/CartesianChart.cs
I've fixed diaplay bug on one-point display.
###[After]
> Fix onepoint display

- src/skiasharp/LiveChartsCore.SkiaSharp/DrawMarginFrame.cs
Ensure LiveCharts is configured before attempting to load the current theme in `DrawMarginFrame`. This update matches the pattern used in other classes that load the theme.
Fixes #53
> Load Theme Correctly in `DrawMarginFrame`

- src/skiasharp/LiveChartsCore.SkiaSharpVew.WinUI/MotionCanvas.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.UWP/MotionCanvas.xaml.cs
When using HIDPI monitor with display scaling set to greater than 100%, chart canvas would not scale correctly. This PR corrects this issue, see before & after pics below:-
> Fixes display scaling in UWP

- src/skiasharp/LiveChartsCore.SkiaSharpVew.WinUI/MotionCanvas.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.UWP/MotionCanvas.xaml.cs
Fixes issue where OnPaintSurface would be called each time we toggle attach visual. This caused behaviour on HIDPI display where canvas would be scaled each time. See before and after pics below:-
> Fixes reattach visual scaling in UWP & WinUI

- src/skiasharp/LiveChartsCore.SkiaSharpView.UWP/DefaultLegend.xaml
- src/skiasharp/LiveChartsCore.SkiaSharpView.UWP/DefaultLegend.xaml.cs
Enabled setting text foreground color in legend by setting LegendTextBrush
Enabled setting legend background by LegendBackground
Fixes #264
> Setting foreground and background for default legend in UWP

- src/LiveChartsCore/Kernel/SeriesProperties.cs
- src/LiveChartsCore/PolarChart.cs
- src/LiveChartsCore/PolarLineSeries.cs
- src/LiveChartsCore/Themes/VisualsStyle.cs
This is a bug fix related to https://github.com/beto-rodriguez/LiveCharts2/issues/271.
The problem was actually with the implementation of PolarCharts. It seems that there was no definition of 'polar' in SeriesProperties.cs for the style object (VisualStyle.cs) to interpret _and_ that the seriesproperty in the PolarLineSeries constructor in core was being set to 'Line'. As far as I can tell, this patch corrects the issue. Polar/Basic is now working as well (same bug in effect there).
> fixed polar bug

- samples/WinUISample/WinUI/WinUI (Package)/WinUISample (Package).wapproj
- samples/WinUISample/WinUI/WinUI/WinUISample.csproj
- samples/XamarinSample/XamarinSample/XamarinSample.Android/Resources/Resource.designer.cs
- src/skiasharp/LiveChartsCore.SkiaSharp/LiveChartsCore.SkiaSharpView.csproj
- src/skiasharp/LiveChartsCore.SkiaSharpVew.WinUI/LiveChartsCore.SkiaSharpView.WinUI.csproj
WinUI projects Microsoft references updated to the latest stable from experimental. SkiaSharp reference updated to 2.88.0-preview.155. Previous latest stable looks like doesn't go along with the latest Microsoft references. Compile gives Page already exists errors for all pages. Strange behavior. Not researched.
> WinUI references update

- src/skiasharp/LiveChartsCore.SkiaSharpView.UWP/MotionCanvas.xaml.cs
DisplayInformation.RawPixelsPerViewPixel property offers wider compatibility with early WinRT versions as shown below :-
https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.displayinformation.rawpixelsperviewpixel
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.xamlroot.rasterizationscale
> Fixes #355 (UWP compatibility issue with Win10 build 17763)

- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/CartesianChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/DefaultLegend.xaml
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/DefaultLegend.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/HeightConverter.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/PieChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/PolarChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/WidthConverter.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Blazor/LiveChartsCore.SkiaSharpView.Blazor.csproj
- src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/CartesianChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/DefaultLegend.xaml
- src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/DefaultLegend.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/HeightConverter.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/PolarChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/WidthConverter.cs
Fixed LegendBackground color issue for Maui and Xamarin Forms (#439), fixed Binding exceptions for conversion to double (issue #429)
> Fixed LegendBackground color issue and Binding exceptions for conversion to double (Xamarin Forms and Maui)

- samples/ViewModelsSamples/Lines/Zoom/ViewModel.cs
- src/LiveChartsCore/CartesianChart.cs
- src/LiveChartsCore/Chart.cs
- src/LiveChartsCore/Kernel/ActionThrottler.cs
- src/LiveChartsCore/Motion/MotionCanvas.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/CartesianChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/CartesianChart.xaml.cs
Now zooming and panning feels more natural, fixed multiple bugs and improvements, now the Cartesian chart control bounces when a user reaches the edge, it should feel more intuitive from a user perspective.
**Desktop**:
**Mobile** (Only Xamarin working correctly for now, Uno and Maui not ready yet)
https://user-images.githubusercontent.com/10853349/165182771-3a5cd49d-c6f3-4253-a9b4-19d106bc09a2.mp4
> Improvements for zooming and panning

- docs/overview/1.2.install.md
- samples/ViewModelsSamples/Axes/ColorsAndPosition/ViewModel.cs
- samples/ViewModelsSamples/Axes/Paging/ViewModel.cs
- samples/ViewModelsSamples/Bars/AutoUpdate/ViewModel.cs
- samples/ViewModelsSamples/Command.cs
- samples/ViewModelsSamples/Events/Cartesian/ViewModel.cs
- samples/ViewModelsSamples/Events/Pie/ViewModel.cs
- samples/ViewModelsSamples/Events/Polar/ViewModel.cs
- samples/ViewModelsSamples/General/Sections/ViewModel.cs
- samples/ViewModelsSamples/General/Sections2/ViewModel.cs
- samples/ViewModelsSamples/Lines/AutoUpdate/ViewModel.cs
- samples/ViewModelsSamples/Maps/World/ViewModel.cs
- samples/ViewModelsSamples/Pies/AutoUpdate/ViewModel.cs
- samples/ViewModelsSamples/Pies/Gauges/ViewModel.cs
- samples/ViewModelsSamples/Scatter/AutoUpdate/ViewModel.cs
- samples/ViewModelsSamples/StepLines/AutoUpdate/ViewModel.cs
- samples/ViewModelsSamples/VisualTest/DataTemplate/ViewModel.cs
- samples/WPFSample/VisualTest/Tabs/View.xaml
- src/LiveChartsCore/Axis.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.WPF/CartesianChart.cs
Some of the view models did not implemented `INotifyPropertyChanged` this caused memory leaks when the view had bindings.
> Fixed memory leaks at least in WPF

- src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/LiveChartsCore.SkiaSharpView.WinUI.csproj
It seems that all other .NET core projects were updated to .NET 6 and this one still referenced .NET 5. Fixing that. Tested resulting binaries in my WinUI app.
> Updated WinUI project to .NET 6.

- samples/ViewModelsSamples/Axes/Crosshairs/ViewModel.cs
- samples/ViewModelsSamples/Index.cs
- samples/WPFSample/Axes/Crosshairs/View.xaml
- samples/WPFSample/Axes/Crosshairs/View.xaml.cs
- src/LiveChartsCore/Axis.cs
- src/LiveChartsCore/Kernel/Sketches/ICartesianAxis.cs
Created a way for making the crosshair "snap" to the closest available ChartPoint. Can be enabled/disabled on a per axis basis
https://user-images.githubusercontent.com/15785664/196917984-4d97c5dc-eab4-40e6-be70-b40f24f90f07.mp4
> Crosshair snapping

- src/LiveChartsCore/Axis.cs
Changing CrosshairPaint / Label to a different color made the Crosshair dissapear entirely. This was because _crosshairLine and _crosshairLabel were not added to the new PaintTasks. Fixed so they will always be added (the Add() is implemented using HashMap, so no duplicates)
> Always add Crosshair Line and Label geo to PaintTask

- src/LiveChartsCore/Kernel/ActionThrottler.cs
Fixes issue #411: Prevents a task cancellation exception from being thrown if a task is cancelled while waiting on the throttler.
> Fixes issue #411.

- src/LiveChartsCore/ColumnSeries.cs
- src/LiveChartsCore/FinancialSeries.cs
- src/LiveChartsCore/HeatSeries.cs
- src/LiveChartsCore/Kernel/ChartPoint.cs
- src/LiveChartsCore/Kernel/ChartPointCleanupContext.cs
- src/LiveChartsCore/Kernel/Drawing/BezierData.cs
- src/LiveChartsCore/Kernel/Extensions.cs
- src/LiveChartsCore/LineSeries.cs
- src/LiveChartsCore/Motion/MotionProperty.cs
- src/LiveChartsCore/PieSeries.cs
- src/LiveChartsCore/PolarLineSeries.cs
- src/LiveChartsCore/RowSeries.cs
- src/LiveChartsCore/ScatterSeries.cs
- src/LiveChartsCore/Series.cs
- src/LiveChartsCore/StepLineSeries.cs
I have been investigating performance and memory issues on my app recently and mentioned that LiveCharts allocate a lot of single use data on every update. This introduces GC pressure which can be avoided.
I created a test workload to highlight those issues. It has 14x4k LineSeries, 4k FinancialSeries, 150k FinancialSeries and 2 ScatterSeries of 8K points on both. Responsiveness in that setup is really bad. It moves, but has huge lags. Though this story is for another time.
This PR focuses on reducing GC allocation on render loop.
Let's take a look at allocations during render (GC Heap Alloc Ignore Free Stacks). I used PerfView Collect command here, app was already started and data loaded for 10-20 seconds. This highlights what types are being constantly allocated.
As we can see main …
> Reduce gc allocations on render loop

- src/LiveChartsCore/Motion/MotionCanvas.cs
While checking #785 I mentioned that you can set `MotionCanvas.Sync` to null in a variety of ways. Originally app crashed because of unhandled exception on thread pool thread which was fixed by PR #776. However [in this comment](https://github.com/beto-rodriguez/LiveCharts2/issues/785#issuecomment-1340009778) I posted another way to crash the app. There is probably a way to achieve same result using all WPF guidelines, instead of setting `DataContext` to `null` explicitly.
Simple solution would be to prevent setting this to `null` since it used a lot internally. 
Stacktrace of crash:
```
Application: TestLvc785.exe
CoreCLR Version: 6.0.1122.52304
.NET Version: 6.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value …
```
> Prevent setting MotionCanvas.Sync to null.

- src/LiveChartsCore/Chart.cs
- src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKDefaultLegend.cs
Issues fixed:
- When legend is shown(left) and hidden there was a big empty space. (`Canvas.StartPoint` was not reset)
- If legend was hidden initially, then left/right legends had horizontal layout (null-coalescing operator prevented changes to `StackPanel`)
- `Series.IsVisibleAtLegend` was completely ignored. Should probably fix #794.
> Fix some legend rendering issues.

- src/LiveChartsCore/ISeries.cs
Exposing MiniatureShapeSize on ISeries interface (that's already implemented in the Series class) allows to customize the theme using `HasRuleForAnySeries` or specialized extensions like `HasRuleForLineSeries`,
> Expose MiniatureShapeSize on ISeries interface

- samples/AvaloniaSample/General/RealTime/View.axaml
- samples/AvaloniaSample/General/RealTime/View.axaml.cs
- samples/BlazorSample/Pages/General/RealTime.razor
- samples/EtoFormsSample/General/RealTime/View.cs
- samples/MauiSample/General/RealTime/View.xaml
- samples/MauiSample/General/RealTime/View.xaml.cs
- samples/UWPSample/General/RealTime/View.xaml
- samples/UWPSample/General/RealTime/View.xaml.cs
- samples/UWPSample/UWPSample.csproj
- samples/UnoPlatformSample/UnoPlatformSample/LiveChartsSamples/General/RealTime/View.xaml
- samples/UnoPlatformSample/UnoPlatformSample/LiveChartsSamples/General/RealTime/View.xaml.cs
- samples/ViewModelsSamples/General/RealTime/ViewModel.cs
- samples/ViewModelsSamples/Index.cs
- samples/WPFSample/General/RealTime/View.xaml
- samples/WPFSample/General/RealTime/View.xaml.cs
- samples/WinFormsSample/General/RealTime/View.Designer.cs
- samples/WinFormsSample/General/RealTime/View.cs
- samples/WinFormsSample/General/RealTime/View.resx
- samples/WinUISample/WinUISample/General/RealTime/View.xaml
- samples/WinUISample/WinUISample/General/RealTime/View.xaml.cs
- samples/XamarinSample/XamarinSample/XamarinSample/General/RealTime/View.xaml
- samples/XamarinSample/XamarinSample/XamarinSample/General/RealTime/View.xaml.cs
- src/LiveChartsCore/Axis.cs
- src/LiveChartsCore/Kernel/Extensions.cs
Adds an example for the following cases:
- #1016
- #1033
> Axes improvements

- samples/BlazorSample/Pages/Hello.razor
It seems like 'is compatible with' phase somehow got duplicated.
> Drop duplicated phrase

- src/skiasharp/LiveChartsCore.SkiaSharpView.Uno.WinUI/LiveChartsCore.SkiaSharpView.Uno.WinUI.csproj
This change avoids a duplicate resources issue that has been fixed in https://github.com/microsoft/microsoft-ui-xaml/issues/8857.
While upgrading WinAppSDK would also fix the issue, it's best to remove the dependency altogether.
Without this fix, the error can appear as follows:
```
ERROR: PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.
ERROR: PRI277: 0x80073b0f - Conflicting values for resource 'Files/Uno.UI.Toolkit/Themes/Generic.xbf'
```
> fix: Make Uno.WinUI conditional to Uno targets

- src/skiasharp/LiveChartsCore.SkiaSharp.WPF/PieChart.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.WPF/PolarChart.cs
Fixes #1489 
The default `legend` assignment in `InitializeCore` was overwriting the user-provided legend.  Moving this to the constructor, similar to how the `tooltip` is managed, yields the desired results.
Example using the [Custom Legend](https://livecharts.dev/docs/WPF/2.0.0-rc2/CartesianChart.Legends#customlegend.cs) example in the `WPFSample` project:
**Before:**
**After:**
> PieChart (and PolarChart) custom legend support (#1489)

- src/LiveChartsCore/CoreAxis.cs
> fixes #1415

- src/LiveChartsCore/CartesianChart.cs
- src/LiveChartsCore/PolarChart.cs
Fixes three cases where logic can flag that internal changes are being made to ChartElement objects and escape the scope without reverting the _isInternalSet flag.  I was actually encountering this on a project where I set the stroke color of a LineSeries based on a condition in the code.  Due to the timing involved, there was a race condition where I was updating the stroke color after the CartesianChart escaped due to the empty bounds with the flag still set, preventing my change from ever being applied.
> Fixing stuck _isInternalSet flag

- src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/MotionCanvas.xaml.cs
Currently, the MAUI MotionCanvas queries MainDisplayInfo on every paint in order to fetch the screen density.
Querying MainDisplayInfo on Android (11, at least) drops into Java interop to call system services - this can take a decent chunk of time, occasionally upwards of 15% of the total paint time in the application I'm profiling.
This PR tweaks the MotionCanvas to query MainDisplayInfo once in the constructor, then register a MainDisplayInfoChanged handler to update it if truly necessary.
Tested on Android, iOS, and Windows with no issues.
> perf: MAUI MotionCanvas - only fetch density from MainDisplayInfo when changed

- samples/AvaloniaSample/Lines/CustomPoints/View.axaml
- samples/AvaloniaSample/Lines/CustomPoints/View.axaml.cs
- samples/BlazorSample/Pages/Lines/CustomPoints.razor
- samples/EtoFormsSample/Lines/CustomPoints/View.cs
- samples/MauiSample/Lines/CustomPoints/View.xaml
- samples/MauiSample/Lines/CustomPoints/View.xaml.cs
- samples/UnoPlatform_v5/UnoPlatform_v5/LiveChartsSamples/Lines/CustomPoints/View.xaml
- samples/UnoPlatform_v5/UnoPlatform_v5/LiveChartsSamples/Lines/CustomPoints/View.xaml.cs
- samples/ViewModelsSamples/Index.cs
- samples/ViewModelsSamples/Lines/CustomPoints/ViewModel.cs
- samples/WPFSample/Lines/CustomPoints/View.xaml
- samples/WPFSample/Lines/CustomPoints/View.xaml.cs
- samples/WinFormsSample/Lines/CustomPoints/View.Designer.cs
- samples/WinFormsSample/Lines/CustomPoints/View.cs
- samples/WinFormsSample/Lines/CustomPoints/View.resx
- samples/WinUISample/WinUISample/Lines/CustomPoints/View.xaml
- samples/WinUISample/WinUISample/Lines/CustomPoints/View.xaml.cs
- samples/XamarinSample/XamarinSample/XamarinSample/Lines/CustomPoints/View.xaml
- samples/XamarinSample/XamarinSample/XamarinSample/Lines/CustomPoints/View.xaml.cs
Adds the next example to the repo and web site:
This sample explains how to create a relation between the DataPoint and the drawn geometry.
Even this was supported from older version, this is now documented and will explain how to solve the next issues:
- #1527
- #1122
> add customPoints sample

- samples/ViewModelsSamples/General/TemplatedLegends/CustomLegend.cs
- samples/ViewModelsSamples/General/TemplatedTooltips/CustomTooltip.cs
- src/LiveChartsCore/BarSeries.cs
- src/LiveChartsCore/CoreBoxSeries.cs
- src/LiveChartsCore/CoreFinancialSeries.cs
- src/LiveChartsCore/CoreHeatSeries.cs
- src/LiveChartsCore/CoreLineSeries.cs
- src/LiveChartsCore/CorePieSeries.cs
- src/LiveChartsCore/CorePolarLineSeries.cs
- src/LiveChartsCore/CoreScatterSeries.cs
- src/LiveChartsCore/CoreStepLineSeries.cs
- src/LiveChartsCore/Kernel/Extensions.cs
- src/LiveChartsCore/Kernel/Sketches/IChartSeries.cs
- src/LiveChartsCore/Series.cs
- src/LiveChartsCore/VisualElements/LineVisual.cs
- src/skiasharp/LiveChartsCore.SkiaSharp/Drawing/Geometries/LineGeometry.cs
- src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKDefaultLegend.cs
- src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKDefaultTooltip.cs
The shape of the series shown in legends/tooltips uses an old api, now the library has better ways to handle that.
This PR updates the library and uses `VisualElements` to define the shapes in the miniature geommetry in tooltips/legends.
It also fixes:
- fixes #1331
That issue has caused confusion in the library, like #1507, #913
> Simplify miniatures

- src/LiveChartsCore/CartesianChart.cs
- src/LiveChartsCore/Measure/AxisLimit.cs
- tests/LiveChartsCore.UnitTesting/OtherTests/AxisTesting.cs
> Inverted axes

- src/LiveChartsCore/CartesianChart.cs
- src/LiveChartsCore/Chart.cs
This PR fixes #1513 
The issue was caused by the logic that bounces back to the chart data when the panning goes out of the limits in the chart, now bouncing behaves much better.
> improve bounce logic

- src/LiveChartsCore/LiveCharts.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.WPF/MotionCanvas.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/CartesianChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/GeoMap.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/MotionCanvas.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/MotionCanvas.xaml
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/PieChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/PolarChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Blazor/MotionCanvas.razor
- src/skiasharp/LiveChartsCore.SkiaSharpView.Blazor/MotionCanvas.razor.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/MotionCanvas.cs
This PR adds a global toggle to enable/disable GPU rendering, i.e. switching from SKCanvasView to SKGLView. This is primarily useful on Android where canvas rendering can be slow. Closes #1645.
~~In draft as this is currently just a prototype for the MAUI view, needs to be extended out to the others~~, but I figured I'd send this to get some feedback.
Figured it would be easier to branch off `dev` for this rather than continuing from `hardware-accelerated`, but happy to move these changes over to there if that's better.
> feat: add global toggle for GPU rendering. closes #1645

- src/LiveChartsCore/Kernel/LiveChartsSettings.cs
- src/LiveChartsCore/Kernel/Sketches/IChartView.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Avalonia/CartesianChart.axaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Avalonia/PieChart.axaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.Avalonia/PolarChart.axaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.WPF/Chart.cs
- src/skiasharp/LiveChartsCore.SkiaSharp.WinForms/Chart.cs
- src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKCartesianChart.cs
- src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKDefaultLegend.cs
- src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKDefaultTooltip.cs
- src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKPieChart.cs
- src/skiasharp/LiveChartsCore.SkiaSharp/SKCharts/SKPolarChart.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Blazor/Chart.razor.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Eto/Chart.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/CartesianChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/PieChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/PolarChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Uno.WinUI/CartesianChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Uno.WinUI/PieChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.Uno.WinUI/PolarChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/CartesianChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/PieChart.xaml.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/PolarChart.xaml.cs
> No nullable dp

- src/LiveChartsCore/Geo/DrawnMap.cs
- src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/LiveChartsCore.SkiaSharpView.WinUI.csproj
- src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/MotionCanvas.cs
This patch improves compatibility with AOT compiled WinUI apps. Fixes https://github.com/beto-rodriguez/LiveCharts2/issues/1889#issue-3122398282:
- AllowUnsafeBlocks is required by the cswinrt source generator
- MotionCanvas needs to be declared partial to generate the necessary code
- Some of the dependencies have been upgraded to AOT compatible versions, matching the winui sample project
- Json source generation is required for the DrawnMap class
> Improve WinUI AOT compatibility

- samples/WinUISample/WinUISample/WinUISample.csproj
- src/skiasharp/LiveChartsCore.SkiaSharpView.WinUI/LiveChartsCore.SkiaSharpView.WinUI.csproj
Apparently, some of the changes made after https://github.com/beto-rodriguez/LiveCharts2/pull/1890 broke AOT compatibility for WinUI apps again (cswinrt source generator does not generate the required files). Updating the Windows App SDK version to 1.7 fixes the issue.
> Update Windows App SDK version to fix AOT issues

- Directory.Build.props
- docs/overview/1.2.install.md
- docs/samples/general/drawOnCanvas/template.md
- docs/samples/lines/zoom/template.md
- samples/AvaloniaSample/General/Sections/View.axaml
- samples/MauiSample/General/Sections/View.xaml
- samples/ViewModelsSamples/General/Sections/ViewModel.cs
- samples/ViewModelsSamples/General/Sections2/ViewModel.cs
- samples/WPFSample/General/Sections/View.xaml
- samples/WinUISample/WinUISample/Samples/General/Sections/View.xaml
> 2.0.0-rc6.1
